### Listar todas las citas
GET http://localhost:8081/citas?page=2&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiaXZhbiIsInJvbGVfaWQiOjMsImlhdCI6MTc2MTIyOTkxMiwiZXhwIjoxNzYxMjU4NzEyfQ.PIx2RLeh28fkfaLHvunf-0MxS1dR58nED5dhv85BHl4
Accept: application/json

### Obtener una cita por ID
GET http://localhost:8081/citas/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Accept: application/json

### Crear una nueva cita
POST http://localhost:8081/citas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Content-Type: application/json

{
  "nombre_cliente": "Sara",
  "telefono_cliente": "555-1234",
  "fecha_hora": "2025-10-27 10:30:00",
  "nombre_trabajador": "Mariaaaa Gomez",
  "id_servicio": 2
}

### Actualizar una cita
PUT http://localhost:8081/citas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Content-Type: application/json

{
  "nombre_cliente": "Juan Perez",
  "telefono_cliente": "555-1234",
  "fecha_hora": "2025-10-27 11:00:00",
  "nombre_trabajador": "Maria Gomez",
  "id_servicio": 2
}

### Eliminar una cita
DELETE http://localhost:8081/citas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU