### Listar todas las reseñas
GET http://localhost:8081/citas?page=2&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiaXZhbiIsInJvbGVfaWQiOjMsImlhdCI6MTc2MTIyOTkxMiwiZXhwIjoxNzYxMjU4NzEyfQ.PIx2RLeh28fkfaLHvunf-0MxS1dR58nED5dhv85BHl4
Accept: application/json

### Obtener una reseña por ID
GET http://localhost:8081/resennas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Accept: application/json

### Crear una nueva reseña
POST http://localhost:8081/resennas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Content-Type: application/json

{
  "nombre_cliente": "Maria Lopez",
  "nombre_trabajador": "Maricela Gomez",
  "calificacion": 5,
  "comentario": "Excelente servicio, ¡muy profesional!",
  "fecha": "2025-10-27"
}

### Actualizar una reseña
PUT http://localhost:8081/resennas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU
Content-Type: application/json

{
  "nombre_cliente": "Ana Looopezz",
  "nombre_trabajador": "Maria Gomez",
  "calificacion": 4,
  "comentario": "El servicio fue bueno, pero la espera fue un poco larga.",
  "fecha": "2025-10-27"
}

### Eliminar una reseña
DELETE http://localhost:8081/resennas/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInVzZXJuYW1lIjoiS2VuaWEiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgxNjY5NjMsImV4cCI6MTc1ODE5NTc2M30.-a2BRPfPf0Uz7KAdR62IwmRNFpofeFsjos8lFi0u0JU