### Listar todas las reseñas
GET http://localhost:8080/resennas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseUZsb3JlcyIsInJvbGVfaWQiOjIsImlhdCI6MTc1Nzg5MTA0MCwiZXhwIjoxNzU3OTE5ODQwfQ.NzesdsMdP6I0hBk7C06Jl1V_kM0Zh0o6X0znlljt9tg
Accept: application/json

### Obtener una reseña por ID
GET http://localhost:8080/resennas/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseUZsb3JlcyIsInJvbGVfaWQiOjIsImlhdCI6MTc1Nzg5MTA0MCwiZXhwIjoxNzU3OTE5ODQwfQ.NzesdsMdP6I0hBk7C06Jl1V_kM0Zh0o6X0znlljt9tg
Accept: application/json

### Crear una nueva reseña
POST http://localhost:8080/resennas
Authorization: Bearer <TOKEN_CLIENTE>
Content-Type: application/json

{
  "nombre_cliente": "Maria Lopez",
  "nombre_trabajador": "Maricela Gomez",
  "calificacion": 5,
  "comentario": "Excelente servicio, ¡muy profesional!",
  "fecha": "2025-10-27"
}

### Actualizar una reseña
PUT http://localhost:8080/resennas/1
Authorization: Bearer <TOKEN_ADMIN>
Content-Type: application/json

{
  "nombre_cliente": "Ana Looopez",
  "nombre_trabajador": "Maria Gomez",
  "calificacion": 4,
  "comentario": "El servicio fue bueno, pero la espera fue un poco larga.",
  "fecha": "2025-10-27"
}

### Eliminar una reseña
DELETE http://localhost:8080/resennas/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJlbWlseUZsb3JlcyIsInJvbGVfaWQiOjIsImlhdCI6MTc1Nzg5MTA0MCwiZXhwIjoxNzU3OTE5ODQwfQ.NzesdsMdP6I0hBk7C06Jl1V_kM0Zh0o6X0znlljt9tg