// Listar todos los servicios
###
GET http://localhost:8080/servicios
Content-Type: application/json

// Obtener un servicio por ID
###
GET http://localhost:8080/servicios/6
Content-Type: application/json

# Crear un nuevo servicio
# Solo admin (token requerido)
###
POST http://localhost:8080/servicios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJqZW1pbWkiLCJyb2xlX2lkIjozLCJpYXQiOjE3NTgwMzk1MzgsImV4cCI6MTc1ODA2ODMzOH0.TI9BssaymoK1glp5bluy3AfaYB0FLCt47pjPxcpZO_c

{
  "nombre_servicio": "Uñas Acrilicas sencillas",
  "descripcion": "uñas acrilicas sencillas",
  "duracion": 3,
  "precio": 15.00
}

# Actualizar un servicio existente
# Solo admin (token requerido)
###
PUT http://localhost:8080/servicios/1
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "nombre_servicio": "Corte de cabello premium actualizado",
  "descripcion": "Incluye lavado, corte y peinado",
  "duracion": 50,
  "precio": 30.00
}

# Eliminar un servicio
# Solo admin (token requerido)
###
DELETE http://localhost:8080/servicios/1
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI
