// Listar todos los servicios
###
GET http://localhost:8080/servicios
Content-Type: application/json

// Obtener un servicio por ID
###
GET http://localhost:8080/servicios/6
Content-Type: application/json

# Crear un nuevo servicio
# Solo admin (token requerido)
###
POST http://localhost:8080/servicios
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "nombre_servicio": "Corte de cabello premium",
  "descripcion": "Incluye lavado y peinado",
  "duracion": 45,
  "precio": 25.00
}

# Actualizar un servicio existente
# Solo admin (token requerido)
###
PUT http://localhost:8080/servicios/1
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI

{
  "nombre_servicio": "Corte de cabello premium actualizado",
  "descripcion": "Incluye lavado, corte y peinado",
  "duracion": 50,
  "precio": 30.00
}

# Eliminar un servicio
# Solo admin (token requerido)
###
DELETE http://localhost:8080/servicios/1
Content-Type: application/json
Authorization: Bearer TU_TOKEN_AQUI
